// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtY_czQcc9VcsG0CulXXzKH4iVOUPOkCc',
    appId: '1:623772180418:web:adb70c75304e5c6bfe405b',
    messagingSenderId: '623772180418',
    projectId: 'walletapp-f4777',
    authDomain: 'walletapp-f4777.firebaseapp.com',
    storageBucket: 'walletapp-f4777.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtY_czQcc9VcsG0CulXXzKH4iVOUPOkCc',
    appId: '1:623772180418:android:adb70c75304e5c6bfe405b',
    messagingSenderId: '623772180418',
    projectId: 'walletapp-f4777',
    storageBucket: 'walletapp-f4777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtY_czQcc9VcsG0CulXXzKH4iVOUPOkCc',
    appId: '1:623772180418:ios:adb70c75304e5c6bfe405b',
    messagingSenderId: '623772180418',
    projectId: 'walletapp-f4777',
    storageBucket: 'walletapp-f4777.firebasestorage.app',
    iosBundleId: 'com.example.demoPages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtY_czQcc9VcsG0CulXXzKH4iVOUPOkCc',
    appId: '1:623772180418:macos:adb70c75304e5c6bfe405b',
    messagingSenderId: '623772180418',
    projectId: 'walletapp-f4777',
    storageBucket: 'walletapp-f4777.firebasestorage.app',
    iosBundleId: 'com.example.demoPages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtY_czQcc9VcsG0CulXXzKH4iVOUPOkCc',
    appId: '1:623772180418:windows:adb70c75304e5c6bfe405b',
    messagingSenderId: '623772180418',
    projectId: 'walletapp-f4777',
    authDomain: 'walletapp-f4777.firebaseapp.com',
    storageBucket: 'walletapp-f4777.firebasestorage.app',
  );
}
